# A: Environment Config
exp_id: 04211700
save_dir: simlpe_out
FPHA_dataset_dir: Hand_pose_annotation_v1
HO3D_dataset_dir: HO3D_v3/train
ARCTIC_dataset_dir: ARCTIC_seqs/splits
seed: 888

# B: Dataset Config
motion:
  step: 1
  input_length: 50
  input_length_dct: ${motion.input_length}
  dim: 63

  train_target_length: 10
  eval_target_length: 25
  normalize_train_data: False
  train_split: p1a_train
  val_split: p1a_val

data_aug: True
deriv_output: True
use_relative_loss: True

# C: Model Config
pre_dct: False
post_dct: False
hidden_dim: 63
motion_mlp:
  hidden_dim: ${hidden_dim}
  seq_len: ${motion.input_length_dct}
  num_layers: 16
  with_normalization: True
  spatial_fc: True
  norm_axis: spatial

motion_fc_in:
  in_features: ${motion.dim}
  out_features: ${hidden_dim}
  with_norm: False
  activation: relu
  init_w_trunc_normal: False
  temporal_fc: True

motion_fc_out:
  in_features: ${hidden_dim}
  out_features: ${motion.dim}
  with_norm: False
  activation: relu
  init_w_trunc_normal: True
  temporal_fc: True

# D: Training Config
batch_size: 128
num_workers: 0
#total_iters: 40000
total_iters: 50000
#lr_max: 3e-4
#lr_min: 1e-5
lr_max: 1e-3
lr_min: 1e-3
weight_decay: 1e-4
model_pth: ""

# E: Evaluation Config
shift_step: 1
metrics: ["MPJPE", "ROOT_Related_MPJPE"]

# E: Display Config
eval_every: 1000
save_every: 50000

# Others
wandb_entity: howbullet
wandb_project: simlpe_train
